#!/usr/bin/env python3
'''
Regenerate board_src.js - an embedded snapshot of the board-side package
used by index.html when it can't fetch() the sources (file:// opening).

Run after any edit to board/wokwi_wokwipwm/:  python3 build_src.py
'''
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
BOARD = os.path.join(HERE, '..', 'board', 'wokwi_wokwipwm')
FILES = ['__init__.py', 'app.py', 'capture.py']

src = {}
for name in FILES:
    with open(os.path.join(BOARD, name)) as f:
        src[name] = f.read()

out = os.path.join(HERE, 'board_src.js')
with open(out, 'w') as f:
    f.write('// generated by build_src.py - do not edit; edit board/wokwi_wokwipwm/ and rerun\n')
    f.write('window.BOARD_SRC = ' + json.dumps(src, indent=1) + ';\n')

print('wrote %s (%d bytes)' % (out, os.path.getsize(out)))
